---
- name: Install Java 1.8
  apt:
    update_cache: true
    name: openjdk-8-jdk
    state: present

- name: Create a Tomcat Group
  group:
    name: tomcat

- name: Create a Tomcat User
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no

- name: Install tomcat on host servers
  apt:
    name: tomcat9
    state: present

- name: Start tomcat service on host servers
  service:
    name: tomcat9
    state: started

- name: Copy WAR file
  copy:
    src: ./addressbook_main/target/addressbook.war
    dest: /usr/share/tomcat9/webapps/

- name: Install Tomcat init script
  copy:
    src: tomcat-initscript.sh
    dest: /etc/init.d/tomcat9
    mode: '0755'
  notify: restart tomcat
